### ISSUE TITLE
ImportError: cannot import name ‘SIT’ from ‘stackstack.trace’

### ISSUE THREAD

**Issue by jasperla** [idiom/stackstack#8]
While `SIT` is imported and used elsewhere:

https://github.com/idiom/stackstack/blob/3c49dec3509ad49c5b1fe25299b6c69213e031cd/src/stackstack.py#L16

`trace.py` is empty and `stackstack` fails to load. Perhaps a file was missed in 79f28ff5a63c40f283e95ecb5990ef3d6b6e894b ? ;-)

**Comment by idiom** [comment]
Thanks for the heads up. Removed import - was removed as I'm refactoring tracing.
